In [8]:
import numpy as np
import pandas as pd
import xgboost as xgb

# 数据接口

#### libsvm

In [53]:
# dtrain = xgb.DMatrix('train.svm.txt')
# dtest = xgb.DMatrix('test.svm.buffer')

#### scipy.sparse array

In [54]:
# csr = scipy.sparse.csr_matrix((dat, (row, col)))
# dtrain = xgb.Dtrain(csr)

#### CSV

In [20]:
dtrain = xgb.DMatrix(data = './data/train.csv?format=csv&label_column=0', 
                     label = None, 
                     missing = np.nan, 
                     weight = None,
                     silent = False,
                     feature_names = None,
                     feature_types = None, 
                     nthread = None)
dtest = xgb.DMatrix('./data/test.csv?format=csv&label_column=0',
                    label = None, 
                    missing = np.nan, 
                    weight = None,
                    silent = False,
                    feature_names = None,
                    feature_types = None, 
                    nthread = None)

[20:05:27] 1461x80 matrix with 116880 entries loaded from ./data/train.csv?format=csv&label_column=0
[20:05:27] 1460x79 matrix with 115340 entries loaded from ./data/test.csv?format=csv&label_column=0


In [26]:
dtrain.feature_names

['f0',
 'f1',
 'f2',
 'f3',
 'f4',
 'f5',
 'f6',
 'f7',
 'f8',
 'f9',
 'f10',
 'f11',
 'f12',
 'f13',
 'f14',
 'f15',
 'f16',
 'f17',
 'f18',
 'f19',
 'f20',
 'f21',
 'f22',
 'f23',
 'f24',
 'f25',
 'f26',
 'f27',
 'f28',
 'f29',
 'f30',
 'f31',
 'f32',
 'f33',
 'f34',
 'f35',
 'f36',
 'f37',
 'f38',
 'f39',
 'f40',
 'f41',
 'f42',
 'f43',
 'f44',
 'f45',
 'f46',
 'f47',
 'f48',
 'f49',
 'f50',
 'f51',
 'f52',
 'f53',
 'f54',
 'f55',
 'f56',
 'f57',
 'f58',
 'f59',
 'f60',
 'f61',
 'f62',
 'f63',
 'f64',
 'f65',
 'f66',
 'f67',
 'f68',
 'f69',
 'f70',
 'f71',
 'f72',
 'f73',
 'f74',
 'f75',
 'f76',
 'f77',
 'f78',
 'f79']

In [28]:
print(dtrain.feature_types)

None


In [30]:
dtrain.get_base_margin()

array([], dtype=float32)

In [33]:
dtrain.get_float_info(field = '')

NameError: name 'f1' is not defined

In [34]:
dtrain.get_label()

array([0.000e+00, 1.000e+00, 2.000e+00, ..., 1.458e+03, 1.459e+03,
       1.460e+03], dtype=float32)

In [35]:
dtrain.get_weight()

array([], dtype=float32)

In [38]:
dtrain.get_uint_info()

TypeError: get_uint_info() missing 1 required positional argument: 'field'

In [39]:
dtrain.num_col()

80

In [40]:
dtrain.num_row()

1461

In [41]:
dtrain.save_binary('./data/house_train.buffer')

#### Numpy array

In [44]:
data = np.random.rand(5, 10)
label = np.random.randint(2, size = 5)
dtrain = xgb.DMatrix(data, label = label)

In [45]:
data

array([[0.90985855, 0.40425695, 0.49539731, 0.71289614, 0.55286594,
        0.44712804, 0.91275809, 0.93366226, 0.73397536, 0.15556806],
       [0.29699645, 0.19274623, 0.01854499, 0.90291336, 0.35858077,
        0.1728208 , 0.9857761 , 0.69450242, 0.88387584, 0.77771175],
       [0.43312232, 0.96110634, 0.88878596, 0.65798185, 0.49035732,
        0.48543716, 0.76985856, 0.80771852, 0.81247471, 0.71999141],
       [0.70090742, 0.21442119, 0.34782528, 0.27341126, 0.72643476,
        0.19214035, 0.7349712 , 0.71393431, 0.9189962 , 0.4087719 ],
       [0.87632917, 0.57003373, 0.55875689, 0.86594065, 0.43664596,
        0.08646045, 0.54644318, 0.9745916 , 0.37252164, 0.5204014 ]])

In [46]:
label

array([0, 0, 1, 1, 0])

In [47]:
dtrain.feature_names

['f0', 'f1', 'f2', 'f3', 'f4', 'f5', 'f6', 'f7', 'f8', 'f9']

In [49]:
print(dtrain.feature_types)

None


#### Pandas DataFrame

In [52]:
data = pd.DataFrame(np.arange(12).reshape((4, 3)), columns = ['a', 'b', 'c'])
label = pd.DataFrame(np.random.randint(2, size = 4))
w = np.random.rand(4, 1)
dtrain = xgb.DMatrix(data = data, label = label, weight = w)